/**
  * @file stwlc68.c
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief Device driver for stwlc68 device
  *
  */

#include "stwlc68.h"



/**
 * @brief initializes device
 * @param dev ptr to stwlc68 device
 * @return status 
 */
static mrt_status_t stw_init(stwlc68_t* dev)
{   
    /* Initialize Register Descriptors */
    REG_INIT( dev->mChipId , STW_REG_CHIP_ID_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mChipRev , STW_REG_CHIP_REV_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mRomId , STW_REG_ROM_ID_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mCfgId , STW_REG_CFG_ID_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mTrimId , STW_REG_TRIM_ID_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mPatchId , STW_REG_PATCH_ID_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mIntEn , STW_REG_INT_EN_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mIntClr , STW_REG_INT_CLR_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mIntLatch , STW_REG_INT_LATCH_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mIntSta , STW_REG_INT_STA_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mOtpLatch , STW_REG_OTP_LATCH_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mOvpLatch , STW_REG_OVP_LATCH_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mOcpLatch , STW_REG_OCP_LATCH_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mSysErr0 , STW_REG_SYS_ERR0_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mSysErr1 , STW_REG_SYS_ERR1_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mSysErr2 , STW_REG_SYS_ERR2_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mDirCmd , STW_REG_DIR_CMD_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mAcFreq , STW_REG_AC_FREQ_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mSStrTx , STW_REG_S_STR_TX_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVoutSet , STW_REG_VOUT_SET_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mVthAoe , STW_REG_VTH_AOE_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mLcrThr , STW_REG_LCR_THR_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mLcrHyst , STW_REG_LCR_HYST_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mModCfg , STW_REG_MOD_CFG_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mIdmylSet , STW_REG_IDMYL_SET_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVrectMin , STW_REG_VRECT_MIN_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropV0 , STW_REG_VDROP_V0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropV1 , STW_REG_VDROP_V1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropV2 , STW_REG_VDROP_V2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropV3 , STW_REG_VDROP_V3_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropC1 , STW_REG_VDROP_C1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropC2 , STW_REG_VDROP_C2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVdropC3 , STW_REG_VDROP_C3_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx0 , STW_REG_MSG_TX0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx1 , STW_REG_MSG_TX1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx2 , STW_REG_MSG_TX2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx3 , STW_REG_MSG_TX3_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx4 , STW_REG_MSG_TX4_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx5 , STW_REG_MSG_TX5_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx6 , STW_REG_MSG_TX6_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx7 , STW_REG_MSG_TX7_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMsgTx8 , STW_REG_MSG_TX8_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mEptMsg , STW_REG_EPT_MSG_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mFodCtc , STW_REG_FOD_CTC_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mFodGsc , STW_REG_FOD_GSC_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mFodOlc , STW_REG_FOD_OLC_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mFodDcr , STW_REG_FOD_DCR_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVrectRe , STW_REG_VRECT_RE_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mRppTx , STW_REG_RPP_TX_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mSsMinTx , STW_REG_SS_MIN_TX_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mCsOffs , STW_REG_CS_OFFS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mIdleCc , STW_REG_IDLE_CC_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mPmaxPtc , STW_REG_PMAX_PTC_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mTrectOtp , STW_REG_TRECT_OTP_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mTlrOtp , STW_REG_TLR_OTP_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mVntcOtp , STW_REG_VNTC_OTP_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mVrectOvp , STW_REG_VRECT_OVP_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mIrectOcp , STW_REG_IRECT_OCP_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mProtEn0 , STW_REG_PROT_EN0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtEn1 , STW_REG_PROT_EN1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtEn2 , STW_REG_PROT_EN2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtEpt0 , STW_REG_PROT_EPT0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtEpt1 , STW_REG_PROT_EPT1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtEpt2 , STW_REG_PROT_EPT2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtOd0 , STW_REG_PROT_OD0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtOd1 , STW_REG_PROT_OD1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mProtOd2 , STW_REG_PROT_OD2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMfrId1 , STW_REG_MFR_ID1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mMfrId0 , STW_REG_MFR_ID0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mBdevId3 , STW_REG_BDEV_ID3_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mBdevId2 , STW_REG_BDEV_ID2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mBdevId1 , STW_REG_BDEV_ID1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mBdevId0 , STW_REG_BDEV_ID0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId7 , STW_REG_XDEV_ID7_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId6 , STW_REG_XDEV_ID6_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId5 , STW_REG_XDEV_ID5_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId4 , STW_REG_XDEV_ID4_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId3 , STW_REG_XDEV_ID3_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId2 , STW_REG_XDEV_ID2_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId1 , STW_REG_XDEV_ID1_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mXdevId0 , STW_REG_XDEV_ID0_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio0Fs , STW_REG_GPIO0_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio1Fs , STW_REG_GPIO1_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio2Fs , STW_REG_GPIO2_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio3Fs , STW_REG_GPIO3_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio4Fs , STW_REG_GPIO4_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio5Fs , STW_REG_GPIO5_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mGpio6Fs , STW_REG_GPIO6_FS_ADDR , uint8_t, REG_PERM_RW , 0x00  );
    REG_INIT( dev->mVrectAdc , STW_REG_VRECT_ADC_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mVoutAdc , STW_REG_VOUT_ADC_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mIrectAdc , STW_REG_IRECT_ADC_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mTrectAdc , STW_REG_TRECT_ADC_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mTlrAdc , STW_REG_TLR_ADC_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mVntcAdc , STW_REG_VNTC_ADC_ADDR , uint16_t, REG_PERM_RW , 0x0000  );


    /*user-block-init-start*/
    /*user-block-init-end*/

    return MRT_STATUS_OK;
}


mrt_status_t stw_init_i2c(stwlc68_t* dev, mrt_i2c_handle_t i2c)
{
    mrt_status_t status;

    status = init_i2c_register_device(&dev->mRegDev, i2c, STWLC68_I2C_ADDRESS, STWLC68_REG_ADDR_SIZE );

    stw_init(dev);


    /*user-block-init-i2c-start*/
    /*user-block-init-i2c-end*/
    
    return status;
}

mrt_status_t stw_test(stwlc68_t* dev)
{
    mrt_status_t status = MRT_STATUS_ERROR;
    /*user-block-test-start*/
    uint16_t chipID;
    chipID = stw_get_chip_id(dev);
    if (chipID == 0x0044)
    {
    	status = MRT_STATUS_OK;
    }
    /*user-block-test-end*/
    return status;
}


/*user-block-bottom-start*/
/*user-block-bottom-end*/
